#!/bin/bash

HERE="`dirname "$0"`"
HERE="`cd "$HERE"; pwd`"
cd "$HERE/../Ads"

ACTION="$1"

if [ "$ACTION" == "on" ]; then
	ACTION=lite
elif [ "$ACTION" == "off" ]; then
	ACTION=plus
fi

if [ "$ACTION" != "lite" -a "$ACTION" != "plus" ]; then
	echo "Usage: $0 <on|off> (or <lite|plus>)" >&2
	exit 1
fi	

if [ -L CurrentSettings.xcconfig ]; then
	rm CurrentSettings.xcconfig
fi

if [ "$ACTION" == "lite" ]; then
	ln -s On.xcconfig CurrentSettings.xcconfig
	cp Lite/* ../
elif [ "$ACTION" == "plus" ]; then
	ln -s Off.xcconfig CurrentSettings.xcconfig
	cp Plus/* ../
fi

"$HERE"/Clobber -configuration Debug
"$HERE"/Clobber
