#!/bin/bash

set -avx

HERE="`dirname "$0"`"
HERE="`cd "$HERE"; pwd`"
cd "$HERE"/..
for i in Build TemporaryItems "Compiled Locales" "Compiled Settings Locales" Applied; do
	if [ -d "$i" ]; then
		rm -Rf "$i"
	fi
done

xcodebuild "$@" clean
